
name: 部署文档

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-from-note-repo]

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          submodules: true
          token: ${{ secrets.BLOG_TOKEN }}

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8


      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: 获取 pnpm store 真实路径并预创建
        run: |
          STORE=$(pnpm store path --silent)
          echo "pnpm store path = $STORE"
          mkdir -p "$STORE"

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 更新所有子模块到最新提交
        run: |
          git submodule update --remote --merge

#      - name: 检查子模块是否有更新
#        id: "check_submodule_change"
#        run: |
#          if [[ `git status --porcelain` ]]; then
#            git add .
#            git commit -m "更新子模块到最新提交"
#            echo "::set-output name=changes::true"
#          else
#            echo "子模块已是最新版本"
#            echo "::set-output name=changes::false"
#          fi
#
#      - name: 推送更新到主分支
#        if: steps.check_submodule_change.outputs.changes == 'true'
#        run: |
#          git push origin main

#     # [错误效果，插件还会参考本地文件时间变化] 使用subtree让 获取历史插件@vuepress/git 获取到note更改信息(插件只能获取本仓库的信息)
#      - name: 获取note
#        run: |-
#          git rm src/note -f
#          git add .
#          git commit -m 'will never commit' # 修复添加subtree错误 fatal: working tree has modifications.  Cannot add.
#          git subtree add --prefix=src/note git@github.com:zwb-233/note.git master

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: src/.vuepress/dist
